### ISSUE TITLE
关于pytorch cuda9.0的问题

### ISSUE THREAD

**Issue by BroadDong** [peterjc123/pytorch-scripts#1]
看您地址在上海，我直接用中文，请教您问题了：
（1）cuda9.bat放到相应的路径中，然后编译，就可以得到想要的版本了。是这个意思吗？
  (2)   conda install -c peterjc123 pytorch cuda90，该命令是直接安装您编译好的pytorch吗？
         pytorch的版本是0.3.0，以及python的版本是3.6吗？

**Comment by peterjc123** [comment]
1. 是的，但是有个参数`DISTUTILS_USE_SDK`好像自动设置不进去，可以在执行脚本前先设置下。
2. 对的，python版本3.5和3.6都行，cuda90就是需要你安装好cuda9。这个是根据官方的0.3branch，加上我之前PR2943和一些其他的修复PR来编译的。

**Comment by BroadDong** [comment]
@peterjc123 ，好的，非常感谢
