### ISSUE TITLE
GPU not supported warnning and application error.

### ISSUE THREAD

**Issue by amilamad** [peterjc123/pytorch-scripts#13]
I am trying to build https://github.com/r9y9/deepvoice3_pytorch project for windows.
I have installed the PyTorch 0.3.1 using the command to use 
`conda install -c peterjc123 pytorch`

But it gives me warning.

> C:\Users\amila.rathnayake\AppData\Local\Continuum\anaconda3\envs\deep_voice_test\lib\site-packages\torch\cuda\__init__.py:116: UserWarning:
    Found GPU0 GeForce GTX 960M which is of cuda capability 5.0.
    PyTorch no longer supports this GPU because it is too old.

Also my script failed with a error in cuda

It was working fine with PyTorch 0.3.0.
Is this a bug or did I do something wrong ?.
and 
how can I revert back to the PyTorch 0.3.0 version ?

**Comment by peterjc123** [comment]
It is expected. The support for old cards is over. To revert back, see the description under the __Easy Installation__ section.

**Comment by amilamad** [comment]
Thank you very much .
