### ISSUE TITLE
Only one core is used in cpu mode.

### ISSUE THREAD

**Issue by psychosomaticdragon** [peterjc123/pytorch-scripts#16]
Current environment: windows 7, conda using python 3.6, fx-8350 cpu.

When i test using torch.get_num_threads() it returns 1. I tried fixing with

torch.set_num_threads(8)

and the number returned by get_num_threads() updates - however pytorch still only uses one thread. I think it has to be specific to the windows port, because running pytorch within a virtual linux environment utilizes all available cores in the virtual machine.

**Comment by peterjc123** [comment]
@psychosomaticdragon This build is compiled with MKL. However, you are using AMD CPU. I think that may be this issue. Would you mind building with source and see if the issue persists?

**Comment by psychosomaticdragon** [comment]
i'll give it a shot, i'm not too familiar with windows builds however - can you point me in the right direction for info on how to build it? Thanks.

**Comment by peterjc123** [comment]
See Compiling Section of README.md.

**Comment by peterjc123** [comment]
#6416 in pytorch/pytorch is on this now.

**Comment by peterjc123** [comment]
It is landed in master.
