### ISSUE TITLE
RuntimeError: cuda runtime error (8) : invalid device function

### ISSUE THREAD

**Issue by emrahyigit** [peterjc123/pytorch-scripts#18]
Hello, 

I just updated everything in my computer and following error started to occur:

RuntimeError: cuda runtime error (8) : invalid device function at c:\anaconda2\conda-bld\pytorch_1519496000060\work\torch\lib\thc\generic/THCTensorMathPointwise.cu:301

Environment is:
Anaconda 5.1.0
Python 3.6.4
Nvidia GTX 860 M 
Nvidia Driver 391

Pytorch installed using following command:

`conda install -c peterjc123 pytorch cuda80`

**Comment by peterjc123** [comment]
@emrahyigit Hi, this is expected. Since the official package has cancelled support for NV cards of which the Compute Capability is below 6.0, you can use the legacy packages or try to compile it yourself.
