### ISSUE TITLE
Nvidia MultiGPU - NCCL

### ISSUE THREAD

**Issue by 5james** [peterjc123/pytorch-scripts#19]
Hello there!
First of all, thanks for pytorch on Windows!
Secondly, are you going to make packages (or tutorial how-to compile pyTorch with your preferences) with features like NCCL, so that we can use multiple GPUs? Right now I'm getting warning: 

> UserWarning: PyTorch is not compiled with NCCL support warnings.warn('PyTorch is not compiled with NCCL support')

James

**Comment by peterjc123** [comment]
The current block is not on the PyTorch side, but the Nvidia side. It is the fact that the missing of NCCL 2 on Windows that prevents the usage of MultiGPU on Windows machines. If you want NCCL, you probably should make some noise in the Nvidia forum and make them realize that. If they released the binaries for Windows, I think it should be easy to compile with it.
