### ISSUE TITLE
Installing Torch Packages

### ISSUE THREAD

**Issue by The-Gupta** [peterjc123/pytorch-scripts#2]
Thank you for creating this and making PyTorch installation simple on Windows. Could you suggest how do I install Torch packages like dp, nngraph, and optim now?

**Comment by peterjc123** [comment]
@The-Gupta Sorry, I don't know how to install Torch. Maybe you should open an issue [here](https://github.com/soumith/torch7)?

**Comment by peterjc123** [comment]
@The-Gupta And a good [repo](https://github.com/hiili/WindowsTorch) for this if you like this.
