### ISSUE TITLE
conda install -c peterjc123 pytorch cuda91 ?

### ISSUE THREAD

**Issue by Aidolii** [peterjc123/pytorch-scripts#21]
One of your suggestions on the pytorch git was I should build from your repo, but there doesn't seem to be a cuda91 package despite there being a cuda91.bat file present.

**Comment by peterjc123** [comment]
Why does there need to be a cuda91 branch? The master branch of official pyTorch is cuda9.1 compatible. If you want v0.3.1, you can pick v0.3.1_win in peterjc123/pytorch.

**Comment by Aidolii** [comment]
Sorry, my edit came too late. I meant to say 'package'.

https://github.com/pytorch/pytorch/issues/494#issuecomment-350527200

Based on what you said here, I would've thought the correct way of doing this would be the command in the title.

**Comment by peterjc123** [comment]
@Aidolii Sorry, there're no compiled packages for cuda9.1. You should compile it by yourself.

**Comment by Aidolii** [comment]
I see. Alright, wish me luck, I only have a vague idea of what I'm doing! :)
