### ISSUE TITLE
\paragon was unexpected at this time

### ISSUE THREAD

**Issue by Aidolii** [peterjc123/pytorch-scripts#22]
I cloned the git and ran cuda91.bat, right after it checks out clang I hit this error:

```
Submodule path 'torch/lib/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
aten\src\ATen\common_with_cwrap.py
1 File(s) copied
\paragon was unexpected at this time.
```

Re-running the script just gives me the same error right away.

Tried searching it before asking, buuut...

![image](https://user-images.githubusercontent.com/37132025/37455680-a55e3932-280b-11e8-8b19-b5218fcc2dba.png)

And I tried seeing if it was just a package I needed...

```
>conda install paragon
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - paragon
```

Any idea?

**Comment by peterjc123** [comment]
Comment out `@echo off` in all scripts and see where the problem is.

**Comment by peterjc123** [comment]
@Aidolii Sorry, I just remembered that you can use cuda80/cuda90 packages even if you have cuda91 installed. The binary files are builtin, so you'll only need any version of CUDA installed.

**Comment by Baddest-Juju** [comment]
What's the difference between the cuda80 and cuda90 version then?

**Comment by peterjc123** [comment]
@Baddest-Juju The builtin binaries are different. For some cards, cuda80 is not supported so they have to use cuda90.

**Comment by Baddest-Juju** [comment]
I found the cause of the error. On line 28 of cuda91.bat (and possibly the others, haven't looked) your path variable isn't quoted properly.

``set PATH=%CUDA_PATH_V9_1%\bin;%PATH%``

should be

``set "PATH=%CUDA_PATH_V9_1%\bin;%PATH%"``
