### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by Baddest-Juju** [peterjc123/pytorch-scripts#23]
```
Script changes needed in this repo
```

PATH variable of cuda bat files not correctly stated, leading to errors when it hits parantheses

``set PATH=%CUDA_PATH_V9_1%\bin;%PATH%``
should be
``set "PATH=%CUDA_PATH_V9_1%\bin;%PATH%"``

setup.bat needs to declare the proper version of VC to compile with.

`call "%VS15VCVARSALL%" x86_amd64`
becomes
``call "%VS15VCVARSALL%" x86_amd64 -vcvars_ver=14.11.25503``

 

```
What the user has to do (that should be documented)
```

The proper components must be installed within the Individual Components tab of Visual Studio Installer (except for the VC2015 one)

![image](https://user-images.githubusercontent.com/33403660/37505182-6abb12c2-28b1-11e8-85a6-6220c048d0d8.png)

A CUDA file must then be modified because it has a check that breaks everything because the _MSC_VER variable does not get correctly passed to it.

>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include\crt\host_config.h

``#if _MSC_VER < 1600 || _MSC_VER > 1911``
becomes
``#if _MSC_VER < 1600``

After all that, it'll compile.

**Comment by peterjc123** [comment]
@Baddest-Juju Thanks for your description. Can you make a PR on this?

**Comment by Baddest-Juju** [comment]
Nope sorry, spent enough time on this already, no offense. I got to get back to paid work.
