### ISSUE TITLE
some pytorch functions cause python crash in windows 7

### ISSUE THREAD

**Issue by sambaiga** [peterjc123/pytorch-scripts#24]
I  installed pytorch for windows successfully. Everything run okay except when I load  some pytorch functions such as  torch.zeros() or torch.ones() python crash with illegal instruction message.

**Comment by sambaiga** [comment]
I fixed by installing intel mkl through conda install -c intel mkl

**Comment by peterjc123** [comment]
But we compiling using the static libraries of MKL, which should not rely on your MKL dlls. I guess the problem is on NumPy.
