### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by MaheshBhosale** [peterjc123/pytorch-scripts#26]
I have installed the right pytorch from [pytorch v0.3.1](https://ci.appveyor.com/project/peterjc123/pytorch-elheu/branch/v0.3.1_win/job/twrldf695ppcwno5) 
I have maxwell GPU QuadroM1200 which is of compute capability 5.0. I am using windows10 64bit. 
Despite of installing all required dependencies, I am getting the below error while importing torch in python interpreter.

(fastai) C:\Users\Mahesh.Bhosale>python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Mahesh.Bhosale\AppData\Local\Continuum\anaconda3\envs\fastai\lib\site-packages\torch\__init__.py", line 76, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
>>> exit()
```
I am not in a position or rather hesitating to build from the source at current moment can you please guide ?

**Comment by peterjc123** [comment]
It's very simple. The CI packages need exactly cuda 8 and cudnn 6.1. Any other versions are rejected.

**Comment by MaheshBhosale** [comment]
But I see from fastai forum that there are ones with cuda 9 and cuda 7.1 working very fine.
http://forums.fast.ai/t/cuda-error-45-no-kernel-image-pytorch-0-3-1-post2/14063/57?u=maheshbhosale

**Comment by MaheshBhosale** [comment]
Also, I didn't got cudnn 6.1 anywhere on NVIDIA websites. Do you have a link?

**Comment by peterjc123** [comment]
Just wait a few days and I'll rebuild for 0.4.0 with cuda 9 and cudnn 7.

**Comment by MaheshBhosale** [comment]
Almighty.  Thanks a lot.

**Comment by peterjc123** [comment]
The CI packages are regenerated now.
