### ISSUE TITLE
Host wheels of pytorch on github

### ISSUE THREAD

**Issue by metya** [peterjc123/pytorch-scripts#27]
Hi peterjc123! 

Thanks for your work with anaconda repo with pytorch! It is great. 

But for many people I think need more flexible installation of pytorch, for cuda91 for example. I noted that you have building different various wheels, but in conda repo located only several ones. 

Maybe is it worth to put this different wheels of pytorch here on github? It would be great.

**Comment by peterjc123** [comment]
Don't worry. There'll soon be wheels and conda packages for cuda80/90/91 hosted on the official site.
