### ISSUE TITLE
issue: Solving environment: failed

### ISSUE THREAD

**Issue by momonala** [peterjc123/pytorch-scripts#3]
I get the following error. I can install pytorch on the smaller `test` environment fine, but when I try to install it outside of the test env. I get the following error. I tried downgrading from Python 3.6.3 to 3.6.0 to no avail. Additionally, if I uninstall for the package that conda questions, I just get the same error with a new package (ex. I uninstalled `xeus` but `qt` now appeared. Any suggestions? 

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - pytorch
  - qt -> icu=58 -> *[track_features=vc14]
  - qt -> icu=58 -> vc==14
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by peterjc123** [comment]
@momonala If you want to do this, please install the offline package.

**Comment by peterjc123** [comment]
@momonala It should be listed [here](https://anaconda.org/peterjc123/pytorch/files).

**Comment by momonala** [comment]
This worked. Thanks!

**Comment by aaryan1210** [comment]
> 
> 
> @momonala It should be listed [here](https://anaconda.org/peterjc123/pytorch/files).

I downloaded the required version of pytorch but have no idea where to paste the extracted files.

**Comment by peterjc123** [comment]
@aaryan1210 What is the error at your side?

**Comment by aaryan1210** [comment]
(base) C:\Users\HP>conda install -c peterjc123 pytorch-cpu
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.



This is the error shown in anaconda prompt.

**Comment by aaryan1210** [comment]
`(base) C:\Users\HP>conda install -c peterjc123 pytorch-cpu
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
`

This is the error shown in anaconda prompt.

**Comment by peterjc123** [comment]
@aaryan1210 Consider using the official one? The one in my repo is outdated.

**Comment by aaryan1210** [comment]
`(base) C:\Users\HP>conda install -c peterjc123 pytorch-cpu

Collecting package metadata (current_repodata.json): done

Solving environment: failed with initial frozen solve. Retrying with flexible solve.

Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

Collecting package metadata (repodata.json): done

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
`

This is the error shown in anaconda prompt.

**Comment by peterjc123** [comment]
@aaryan1210 Please try `conda install -c pytorch pytorch cpuonly`.

**Comment by aaryan1210** [comment]
I have a Cuda 9.2 toolkit installed and I downgraded my python version to 3.5 to match the version shown in error.

**Comment by aaryan1210** [comment]
> 
> 
> @aaryan1210 Please try `conda install -c pytorch pytorch cpuonly`.
Thanks a lot, this worked.

**Comment by aaryan1210** [comment]
> 
> 
> @aaryan1210 Please try `conda install -c pytorch pytorch cpuonly`.

Hey, I installed PyTorch using the above-mentioned code, but today the prompt is showing that no module named torch exists.  

`import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'`

**Comment by peterjc123** [comment]
@aaryan1210 You have multiple python installation? What is the result of the following commands?
```
where conda
where python
```

**Comment by aaryan1210** [comment]
Yes, I have 2 python installations and 3 conda installations.

`F:\ProgramFiles\Anaconda3\Library\bin\conda.bat`
`F:\ProgramFiles\Anaconda3\Scripts\conda.exe`
`F:\ProgramFiles\Anaconda3\condabin\conda.bat`

And python

`F:\ProgramFiles\Anaconda3\python.exe`
`C:\Users\HP\AppData\Local\Microsoft\WindowsApps\python.exe`

**Comment by peterjc123** [comment]
@aaryan1210 There is nothing wrong there. Maybe you installed it into a virtual environment?

**Comment by aaryan1210** [comment]
Which files should I delete?

**Comment by aaryan1210** [comment]
I installed with (base) file.

**Comment by peterjc123** [comment]
Could you please show me the result of `conda info -e`?

**Comment by aaryan1210** [comment]
I installed with (base) and I tried installing it in a virtual environment. But installed it in (base) too.

**Comment by aaryan1210** [comment]
`base                  *  F:\ProgramFiles\Anaconda3`
`myenv                    F:\ProgramFiles\Anaconda3\envs\myenv`

**Comment by peterjc123** [comment]
What about `conda list pytorch` and `pip show torch`?

**Comment by aaryan1210** [comment]
`# packages in environment at F:\ProgramFiles\Anaconda3:`
`#`
`# Name                    Version                   Build  Channel`

And pip didn't show any result.

**Comment by aaryan1210** [comment]
I think think this means no pytorch is installed.

**Comment by peterjc123** [comment]
So it seems `pytorch` is not installed in this env. Just try to install it again.

**Comment by aaryan1210** [comment]
Should I download it in env or base?

**Comment by peterjc123** [comment]
@aaryan1210 Just according to your needs. Both should work.

**Comment by aaryan1210** [comment]
Ok, installation in env is working properly but the base* is showing error.

**Comment by peterjc123** [comment]
What error is it?

**Comment by aaryan1210** [comment]
hey can you help me in installing kivy.... conda-forge shows lots of errors. Tried -pip too but it didnt help at all.
