### ISSUE TITLE
pytorch 0.4 for windows

### ISSUE THREAD

**Issue by arpitvw** [peterjc123/pytorch-scripts#32]
when can we expect pytorch 0.4 update for windows, as many of the 0.4 commands are not supporting 0.3.1 version
1) module 'torch' has no attribute 'device'

2)'torch.FloatTensor' object has no attribute 'to'

3) AttributeError: 'ResNet' object has no attribute 'to'

**Comment by peterjc123** [comment]
@arpitvw Why don't you use the official 0.4 package?

**Comment by peterjc123** [comment]
Please use the packages on https://pytorch.org/
