### ISSUE TITLE
Adding build_windows_shared_vs2015.bat

### ISSUE THREAD

**Issue by ArutyunovG** [peterjc123/pytorch-scripts#39]
Hi. @peterjc123,

I'm almost done with Visual Studio 2015 Caffe2 build. 
The final checks required are testing build with OpenCV in Debug mode.

Please, suggest me a place where to commit the script in your repo when the work is finished? Probably it is better to create specific folder?

Do you have glog, gflags, lmdb and OpenCV for VS2015 that CMake can catch? It would be cool to fully-test script functionality on your separate PC.
LMDB for Windows can be found [here](https://github.com/willyd/lmdb/tree/d778142df09bb4a4cd3909773f054e78c60f3ddf/libraries/liblmdb)

Thanks,
Grigory

**Comment by peterjc123** [comment]
Yes, maybe you'll need a new directory. Feel free to create one. You can actually test that through CI. The Azure pipelines are free.
