### ISSUE TITLE
PyTorch v0.3.1

### ISSUE THREAD

**Issue by maciejkula** [peterjc123/pytorch-scripts#5]
Thanks for providing the Windows packages!

Just wanted to mention that I'm trying to cut a new release of https://github.com/maciejkula/spotlight, and I have made the switch to v0.3.1.

Can I give a hand with pushing the v0.3.1 conda packages in any way?

**Comment by peterjc123** [comment]
Sorry, it's currently Spring Festival in China. I'll try to make a new build with CI. The conda packages may be available later.

**Comment by maciejkula** [comment]
Thank you, please make sure to enjoy the holiday and ignore me until it's finished :)

**Comment by peterjc123** [comment]
@maciejkula The CPU packages are available through the following command:
```
conda install -c peterjc123 pytorch-cpu
```

**Comment by peterjc123** [comment]
@maciejkula The full packages are updated. Please enjoy.

**Comment by maciejkula** [comment]
Will do. Thank you!
