### ISSUE TITLE
Error when running cuda100.bat: Error : Internal Compiler error (codegen): "there was an error in verifying the lgenfe output!"

### ISSUE THREAD

**Issue by Maosef** [peterjc123/pytorch-scripts#55]
Been trying to build Pytorch from source in Windows 10, really stuck here. Using Anaconda.

INPUT

(torchTest) C:\Users\pazzu\Documents\pytorch-scripts>cuda100
Ninja not found. It can be used to accelerate builds.
You can install ninja using `pip install ninja`.
MAGMA_HOME is set. MAGMA will be included in build.
The flags after configuration:
NO_CUDA=
CMAKE_GENERATOR=Visual Studio 15 2017 Win64
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
DISTUTILS_USE_SDK=1
Do you wish to continue? (Y/N)

OUTPUT
....
"C:\Users\pazzu\Documents\pytorch-scripts\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"C:\Users\pazzu\Documents\pytorch-scripts\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\pazzu\Documents\pytorch-scripts\pytorch\build\caffe2\AlgorithmsTest.vcxproj" (default target) (4) ->
"C:\Users\pazzu\Documents\pytorch-scripts\pytorch\build\caffe2\caffe2_gpu.vcxproj" (default target) (22) ->
(CustomBuild target) ->
  Error : Internal Compiler error (codegen): "there was an error in verifying the lgenfe output!" [C:\Users\pazzu\Docum
ents\pytorch-scripts\pytorch\build\caffe2\caffe2_gpu.vcxproj]

    32851 Warning(s)
    1 Error(s)

Time Elapsed 02:18:20.84

(torchTest) C:\Users\pazzu\Documents\pytorch-scripts\pytorch\build>IF ERRORLEVEL 1 exit 1
Failed to run 'tools\build_pytorch_libs.bat --use-cuda --use-nnpack --use-mkldnn --use-qnnpack caffe2'

**Comment by peterjc123** [comment]
Is there an error prior to this?

**Comment by Maosef** [comment]
I don't think so. The pasted text was the only part that was red.

**Comment by peterjc123** [comment]
Which version of VS are you using?

**Comment by Maosef** [comment]
Visual Studio Community 2017, 15.9.3

**Comment by Maosef** [comment]
I rebuilded and it worked, thanks! Not sure what went differently except for installing Ninja.
