### ISSUE TITLE
does python 2.x work?

### ISSUE THREAD

**Issue by dongshuhao** [peterjc123/pytorch-scripts#6]
Hey Peter, a very nice work!  I am wondering that whether pytorch can be compiled with python 2.x? Based on my understanding, it seems it requires python 3.5 or up to compile the pytorch on Windows, right?

**Comment by peterjc123** [comment]
It can be compiled, but the quality cannot be ensured. It's better to compile it using python 3.5 or up.

**Comment by mingfengwan** [comment]
A stupid question: how do I install this in conda under the python2.x environment? I need to use python 2.7 for my coursework :(

**Comment by peterjc123** [comment]
There's no compiled package. You have to compile it by yourself with the help of this repo. The info in the README.md is sufficient for you.
