### ISSUE TITLE
Getting STMVOS to work with Pytorch using an NVIDIA 1070 GTX GPU

### ISSUE THREAD

**Issue by OneWorld-github** [peterjc123/pytorch-scripts#60]
Hi Peter, I hope you are well, I was wondering if you would be able to suggest a way forward with this ?
I am trying to get this code to work:- https://github.com/seoungwugoh/STM
It requires a Pytorch install.

I have Windows 10, an NVIDIA GTX 1070 GPU.

I also tried the instructions from this post
https://gist.github.com/Ravi2712/47f070a6578153d3caee92bb67134963 

I have another fuller report about this here:-
https://stackoverflow.com/questions/62088265/runtimeerror-attempting-to-deserialize-object-on-a-cuda-device-but-torch-cuda-i

My Drivers and GPU details are as follows:-

`
C:\Program Files\NVIDIA Corporation\NVSMI>nvidia-smi.exe
Mon Jun 01 13:09:20 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 441.22       Driver Version: 441.22       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070   WDDM  | 00000000:01:00.0  On |                  N/A |
| 57%   80C    P2   134W / 151W |    967MiB /  8192MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
`

I tried conda install -c peterjc123 pytorch cuda90
However, STM VOS also requires torchvision.

So I tried the install suggestion from here
https://gist.github.com/Ravi2712/47f070a6578153d3caee92bb67134963 

`
(STMVOS) C:\Users\OneWorld\Documents\DeepLearning\VideoObjectSegmentation\STMVOS>pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
Successfully installed future-0.18.2 torch-1.5.0+cu101 torchvision-0.6.0+cu101
`

`
(STMVOS) C:\Users\OneWorld\Documents\DeepLearning\VideoObjectSegmentation\STMVOS>python eval_DAVIS.py -g '1' -s val -y 17 -D C:\Users\OneWorld\Documents\DeepLearning\VideoObjectSegmentation\DAVIS2017SemiSupervisedTrainVal480
Space-time Memory Networks: initialized.
STM : Testing on DAVIS
Loading weights: STM_weights.pth
Traceback (most recent call last):
  File "eval_DAVIS.py", line 111, in <module>
    model.load_state_dict(torch.load(pth_path))
  File "C:\Users\OneWorld\anaconda3\envs\STMVOS\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\OneWorld\anaconda3\envs\STMVOS\lib\site-packages\torch\serialization.py", line 773, in _legacy_load
    result = unpickler.load()
  File "C:\Users\OneWorld\anaconda3\envs\STMVOS\lib\site-packages\torch\serialization.py", line 729, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "C:\Users\OneWorld\anaconda3\envs\STMVOS\lib\site-packages\torch\serialization.py", line 178, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\OneWorld\anaconda3\envs\STMVOS\lib\site-packages\torch\serialization.py", line 154, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\OneWorld\anaconda3\envs\STMVOS\lib\site-packages\torch\serialization.py", line 138, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
`

However, my test below shows that cuda is available is true here.

(STMVOS) C:\Users\OneWorld\Documents\DeepLearning\VideoObjectSegmentation\STMVOS>python
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True

So I was wondering, what do you think the issue is?  Or what would you suggest to do to get Space Time Memory Networks ( https://github.com/seoungwugoh/STM ) to work with my Nvidia 1070 GTX GPU and Pytorch.

**Comment by OneWorld-github** [comment]
here is the answer to this one

https://stackoverflow.com/questions/62088265/runtimeerror-attempting-to-deserialize-object-on-a-cuda-device-but-torch-cuda-i

**Comment by peterjc123** [comment]
@OneWorld-github I'm glad you figured it out.
