### ISSUE TITLE
vc 14.1 package missing DLLs

### ISSUE THREAD

**Issue by dhirschfeld** [peterjc123/pytorch-scripts#8]
The `vc=14.1` package appears to be missing some DLLs so breaks conda build on my Win7 machine:

![](https://files.gitter.im/conda/conda-build/tndj/image.png)

See discussion at https://gitter.im/conda/conda-build?at=5a94acef35dd17022efa734d

I do have VS2017 installed so this doesn't affect my normal day-to-day usage. conda build however creates a clean environment and it appears that when `vc=14.1` is installed in this environment python can't start because of the missing DLLs (IIUC).

**Comment by peterjc123** [comment]
@dhirschfeld I don't fully understand your description. Is vc14.1 breaking your build process or the package at runtime? If you cannot compile when vc14.1 is installed, then it should be okay, for it is only useful to confirm the package to run on client machines. If the error was thrown at runtime, then it should be the issue at my side. 
Anyway, I'll keep this issue open to keep track. Further discussion is welcomed.

**Comment by dhirschfeld** [comment]
IIUC python itself won't load with `vc=14.1` (instead of vc=14`) unless you happen to have VS2017 installed on your PC because the `vc=14.1` package is missing some required DLLs.

I haven't had a chance to dig deeper yet so my diagnosis might be incorrect - just wanted to make a note of it so I can come back to it and investigate further when I have the time  / when it's on the critical path!

**Comment by peterjc123** [comment]
@dhirschfeld I've checked the packages and found that the DLLs are stored in the package `vs2017_runtime`. Would you please try if the issue persists after installing that package?

**Comment by peterjc123** [comment]
@dhirschfeld Well, after checking this [post](https://social.msdn.microsoft.com/Forums/en-US/a28331ae-19a3-4a34-b3ba-1e8fd4430375/missing-apimswincore-dlls?forum=windowsgeneraldevelopmentissues), the actual problem was revealed. When VS2017 is used in build, some features may not work in Windows 7. It is not only the copy-paste that can resolve this issue, since these files are OS dependent. That is to say, we have to build the code on Windows 7 to make it work, not Windows 8/8.1.

**Comment by peterjc123** [comment]
@dhirschfeld The `vc` package has been updated. You can try if that helps.

**Comment by peterjc123** [comment]
@dhirschfeld If there is no problem there, I'll close this issue.

**Comment by dhirschfeld** [comment]
Thanks for the quick fix! I'll try and test it shortly. Happy to close this now - in case there are any further issues it can always be reopened...

**Comment by dhirschfeld** [comment]
Just noting here Mike's response:
https://gitter.im/conda/conda-build?at=5a996e0c888332ee3aef1484

> *the recipe for bundling runtimes was wrong. It was pointed at an incorrect subfolder that bundles DLLs with too many deps (for a different purpose)
See https://github.com/msarahan/aggregate/blob/master/vs2017/install_runtime.bat#L30 for the correct path (does NOT have OneCore in it)*

**Comment by peterjc123** [comment]
@dhirschfeld Yes, I've already noticed this and the vc package is already updated before the closing of this issue. Thanks for reminding me.
